export enum ControllersUrlEnums {
  city = '/City',
  authentication = '/Authentication',
  role = '/Role',
  userRole = '/UserRole',
  roleUserPermission = '/RoleUserPermission',
  common = '/Common',
  wornMaster = '/WornMaster',
  product = '/Product',
  message = '/Message',
  order = '/Order',
  productGroup = '/ProductGroup',
  payment = '/Payment',
  orderTransaction = '/OrderTransaction',
}
